Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,18 +1,77 @@
-name: Docker Image CI
+name: EKS Deployment Pipeline
 
 on:
+  workflow_dispatch: {}
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
+    branches: #Evaluate if we are going to remove this trigger or not
+      - project_8
+ 
 jobs:
-
-  build:
-
+  build-and-deploy:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Build the Docker image
-      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
+      #Step 1: Checkout code from the project folder to GitHub Server
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Get directory
+        run: |
+          ls
+          pwd
+
+      #Step 2: Test application, we'll use docker-compose to test the application.
+      - name: Test application 
+        run: |
+          
+          cd project_8/section_3
+          sudo docker-compose -f docker-compose.yml up -d
+          sleep 60
+          if sudo docker-compose logs app | grep -q "Connected to MongoDB successfully"; then
+            echo "Test succeeded: 'Connected to MongoDB successfully' found in logs"
+            sudo docker-compose down
+          else
+            echo "Test failed: 'Connected to MongoDB successfully' not found in logs"
+            sudo docker-compose -f docker-compose.yml down
+            exit 1  #Exit with a non-zero status to indicate test failure
+          fi
+      
+      #Step 3: Build Docker image from the DockerFiles
+      - name: Build Docker images for NodeJS app and MongoDB
+        run: |
+          cd project_8/section_3
+
+          #Build NodeJS app image
+          docker build -t project8app -f Dockerfile.app .
+
+          #Build MongoDB image
+          docker build -t project8mongodb -f Dockerfile.mongodb .
+
+          #Log in to Docker Hub
+          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
+
+          #Push the images
+          docker tag project8app santospardos/sanvalero:project8app
+          docker push santospardos/sanvalero:project8app
+          docker tag project8app santospardos/sanvalero:project8mongodb
+          docker push santospardos/sanvalero:project8mongodb
+
+      #Step 4: Deploy application to EKS
+      - name: Deploy to EKS
+        run: |
+          
+          #Set up AWS credentials
+          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws configure set aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+          aws configure se aws-region: ${{env.AWS_REGION}}
+
+          #Update kubeconfig for EKS cluster
+          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
+
+          #Apply Kubernetes manifests
+          cd project_8/section_3
+          kubectl apply -f mongo-service.yaml
+          kubectl apply -f mongo-deployment.yaml
+          kubectl apply -f app-service.yaml
+          kubectl apply -f app-deployment.yaml
